version: "3"

services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ${PROJECT_PATH}:/workspace
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    container_name: swoole_nginx
    networks:
      - app-network
  
  php:
    build: 
      context: php/
      args:
        SWOOLE_VERSION: ${SWOOLE_VERSION}
        TIMEZONE: ${TIMEZONE}
    depends_on:
      - mariadb
      - redis
    volumes:
      - ${PROJECT_PATH}:/workspace
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
    container_name: swoole_php
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      TZ: ${TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./conf/mariadb/my.cnf:/etc/mysql/my.cnf
      - ./logs/mariadb:/var/log/mariadb
    container_name: swoole_mariadb
    networks: 
      - app-network
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis:/data/redis
    # 以自定义配置文件启动 redis
    command: redis-server /etc/redis/redis.conf
    container_name: swoole_redis
    networks: 
      - app-network

networks:
  app-network:
    driver: bridge